<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder {
    public function run(): void {
        DB::table('users')->insert([
            [
                'id'                => 1,
                'name'              => 'Administrator',
                'email'             => 'admin@perpustakaan.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('12345678'),
                'terms_and_policy'  => 1,
                'avatar'            => null,
                'google_id'         => null,
                'apple_id'          => null,
                'role'              => 'admin',
                'status'            => 'active',
                'phone'             => '081234567890',
                'address'           => 'Jl. Admin No. 1, Jakarta',
                'member_id'         => 'ADM001',
                'date_of_birth'     => '1985-01-01',
                'join_date'         => now()->format('Y-m-d'),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
                'deleted_at'        => null,
            ],
            [
                'id'                => 2,
                'name'              => 'Staff Perpustakaan',
                'email'             => 'staff@perpustakaan.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('12345678'),
                'terms_and_policy'  => 1,
                'avatar'            => null,
                'google_id'         => null,
                'apple_id'          => null,
                'role'              => 'staff',
                'status'            => 'active',
                'phone'             => '081234567891',
                'address'           => 'Jl. Staff No. 2, Jakarta',
                'member_id'         => 'STF001',
                'date_of_birth'     => '1990-02-02',
                'join_date'         => now()->format('Y-m-d'),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
                'deleted_at'        => null,
            ],
            [
                'id'                => 3,
                'name'              => 'Guru Matematika',
                'email'             => 'guru@perpustakaan.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('12345678'),
                'terms_and_policy'  => 1,
                'avatar'            => null,
                'google_id'         => null,
                'apple_id'          => null,
                'role'              => 'teacher',
                'status'            => 'active',
                'phone'             => '081234567892',
                'address'           => 'Jl. Guru No. 3, Jakarta',
                'member_id'         => 'GRU001',
                'date_of_birth'     => '1988-03-03',
                'join_date'         => now()->format('Y-m-d'),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
                'deleted_at'        => null,
            ],
            [
                'id'                => 4,
                'name'              => 'Siswa SMA',
                'email'             => 'siswa@perpustakaan.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('12345678'),
                'terms_and_policy'  => 1,
                'avatar'            => null,
                'google_id'         => null,
                'apple_id'          => null,
                'role'              => 'student',
                'status'            => 'active',
                'phone'             => '081234567893',
                'address'           => 'Jl. Siswa No. 4, Jakarta',
                'member_id'         => 'SIS001',
                'date_of_birth'     => '2005-04-04',
                'join_date'         => now()->format('Y-m-d'),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
                'deleted_at'        => null,
            ],
        ]);
    }
}
